name: key-testing

on:
  schedule:
    - cron:  '*/5 * * * *'


jobs:
        deploy-new-version:
                runs-on: ubuntu-latest
                steps:
                      - uses: actions/checkout@v2
                      - name: Set up JDK 1.8
                        uses: actions/setup-java@v1
                        with:
                              java-version: 1.8
                      - name: Test the Key
                        env:
                            STUPID_KEY: ${{ secrets.STUPID_KEY }}
                            GITTHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
                            WEBID_PKG: ${{ secrets.WEBID_PKG }} 
                        run: |
                          echo "$STUPID_KEY"
                          echo "$WEBID_PKG" > ~/.m2/webid_pkg.p12
                      
