name: 

on:
  schedule:
    - cron:  '*/30 * * * *'


jobs:
        deploy-new-version:
                - uses: actions/checkout@v2
                runs-on: ubuntu-latest
                steps:
                        - name: Run Script
                          env:
                                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                                WEBID_KEY: ${{ secrets.WEBID_KEY}}
                          run: |
                            cd ontology/
                            git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
                            eval `ssh-agent -t 60 -s`
                            echo "$GITHUB_TOKEN" | ssh-add -
                            mkdir -p ~/.ssh/
                            ssh-keyscan github.com >> ~/.ssh/known_hosts

                            mkdir ~/.m2/
                            echo "$WEBID_KEY" > ~/.m2/webid_bundle.p12
                            bash  -c databus-ontology-diffbot.sh

            

