name: Ontology-tracker

on:
  schedule:
    - cron:  '0 0 */7 * *'


jobs:
        deploy-new-version:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Set up JDK 1.8
                          uses: actions/setup-java@v1
                          with:
                                java-version: 1.8
                        - name: Run Script
                          env:
                                SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
                                WEBID_KEY: ${{ secrets.WEBID_KEY }}
                                WEBID_CRT: ${{ secrets.WEBID_CRT }} 
                          run: |
                            sudo apt-get install raptor2-utils
                            eval $(ssh-agent -s)
                            mkdir -p ~/.ssh
                            chmod 700 ~/.ssh
                            echo "$SSH_DEPLOY_KEY" | ssh-add -
                            
                            echo "$WEBID_KEY" > ~/.m2/webid_key.pem
                            echo "$WEBID_CRT" > ~/.m2/webid_crt.pem
                            openssl pkcs12 -export -out ~/.m2/webid_bundle.p12 -inkey ~/.m2/webid_key.pem -in ~/.m2/webid_crt.pem
                            bash  -c ontology/databus-ontology-diffbot.sh
