name: Ontology-tracker

on:
  schedule:
    - cron:  '*/5 * * * *'


jobs:
        deploy-new-version:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Set up JDK 1.8
                          uses: actions/setup-java@v1
                          with:
                                java-version: 1.8
                        - name: Run Script
                          env:
                                SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
                                WEBID_PKG: ${{ secrets.WEBID_PKG }}
                          run: |
                            sudo apt-get install raptor2-utils
                            eval $(ssh-agent -s)
                            mkdir -p ~/.ssh
                            chmod 700 ~/.ssh
                            echo "$SSH_DEPLOY_KEY" | ssh-add -

                            echo "$WEBID_PKG" > ~/.m2/webid_bundle.p12
                            echo "Validating pkcs12 file..."
                            openssl pkcs12 -in ~/.m2/webid_bundle.p12 -out ~/testing_cert.pem -nodes
                            echo "Done!"
                            bash  -c ontology/databus-ontology-diffbot.sh
