name: Ontology-tracker

on:
  schedule:
    - cron:  '*/5 * * * *'


jobs:
        deploy-new-version:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Set up JDK 1.8
                          uses: actions/setup-java@v1
                          with:
                                java-version: 1.8
                        - name: Run Script
                          env:
                                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                                WEBID_KEY: ${{ secrets.WEBID_KEY}}
                          run: |
                            eval $(ssh-agent -s)
                            mkdir -p ~/.ssh
                            chmod 700 ~/.ssh
                            echo "$GITHUB_TOKEN" | ssh-add - > ~/.ssh/id_rsa
                            cd ontology/
                            git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
                            ssh-keyscan github.com >> ~/.ssh/known_hosts

                            mkdir ~/.m2/
                            echo "$WEBID_KEY" > ~/.m2/webid_bundle.p12
                            bash  -c databus-ontology-diffbot.sh
